### PR TITLE
Feature/readme

### LINKED ISSUE #11: Rules in README
It would be good to get all the rules and specifics on how the game is going to work written up in the `README` so we can reference it while coding

### PR DESCRIPTION
**Pull request by lynchgeorge**
Updating the README file to contain overview of game mechanics. 
Included: Rules, Decks, Cards, Attack/Damage

### CODE REVIEW

**Review by dixonary — COMMENTED** [review]
Add two newlines between paragraphs, otherwise Markdown (at least, as rendered on Github!) mushes it all into the same paragraph :)

**Comment by dixonary** [comment]
You can see this by clicking on the "display the rich diff" button in the header when looking at the commit diff on GitHub.

Text content all looks good!

**Comment by mbg** [comment]
> You can see this by clicking on the "display the rich diff" button in the header when looking at the commit diff on GitHub.

That looks fine to me. I was about to link to that:

https://github.com/fpclass/perpetual-haskelling-initiative/pull/12/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by dixonary** [comment]
There are lots of cases where newlines are not being respected by markdown, so it ends up with things like

```
[...] behaviours of programming paradigms Cards from an EXPANSION [...]
```

**Comment by dixonary** [comment]
Given that all the content is there and that's enough for other people to go on, I'll approve :)

**Review by dixonary — APPROVED** [review]

**Comment by mbg** [comment]
@GLynch-code Do you just want to add yourself to the `AUTHORS` file?

**Comment by ghost** [comment]
Will there be a max amount of programs a player can have in play at once or is it as many as the player is able to play?

**Comment by lynchgeorge** [comment]
There should be a limit, ill set it to 8 for now, ans then with game play we could change at a later date. Im pretty sure 8 is the hearthstone limit too although I could be wrong

**Review by ghost — APPROVED** [review]

**Review by oscar-h64 — APPROVED** [review]

**Pull request merged**
