### PR TITLE
Create Player.hs file

### PR DESCRIPTION
**Pull request by ghost**
Started on the data types for the player.

I know the player will need to include the deck, hand, current points, maximum points, board space, dead programs.

### CODE REVIEW

**Comment by oscar-h64** [comment]
I think it's best practise to prefix the fields in records with the record name, like in `Card`, because it avoids clashes. 

I also don't know if `Deck` should be it's own module like `Hand`

**Comment by ghost** [comment]
Should I let this be merged into develop so people can use these if they are adding to the features?

**Comment by mbg** [comment]
Sure, if there's nothing else you want to add at this stage!

**Review by mbg — APPROVED** [review]

**Review by oscar-h64 — APPROVED** [review]

**Comment by ghost** [comment]
Yeah, I have some stuff I need to do so I won't be able to do more work right now.

**Pull request merged**
