### PR TITLE
Basic game types

### PR DESCRIPTION
**Pull request by mbg**
This PR adds some basic game types.

### CODE REVIEW

**Comment by oscar-h64** [comment]
In terms of having the 3 different types of card, would it be sufficient to add something like
```haskell
data CardType = CardProgram | CardError | CardEvent
```
Then add another field to the `Card` record to describe the card type, then the effect would be determined by what's in `Program`, or is it going to be more complex than that?

**Comment by dixonary** [comment]
If the different card types have different properties, then it might be more type-safe for the cards to be instances of one of three types.

So it would be like
```
data Card
 = CardProgram {...} 
 | CardError {...}
```
since, say, Error cards won't have a casting cost, nor an attack value.

**Comment by oscar-h64** [comment]
Ah yeah. I don't know what fields different cards need, we only have name, description, paradigm and program in the `Card` definition. I think we probably need to decide the specifics on how the game works before the code can go any further

**Comment by mbg** [comment]
I think it may be good to merge this with just simple definitions that we can then build on, rather than trying to delegate the entire development to this branch.

**Review by oscar-h64 — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Pull request merged**
